version: "3.9"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=yourpassword
      - MYSQL_DB=pos_system
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: pos_system
    volumes:
      - db_data:/var/lib/mysql
      - ./database/pos_system.sql:/docker-entrypoint-initdb.d/pos_system.sql

volumes:
  db_data: